name: "Next Minor"

on:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:

env:
  version: nextminor
  appVersion: '19.1'
  appBuild: 2147483647
  appRevision: 0

defaults:
  run:
    shell: PowerShell

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run pipeline
        uses: juliandittmann/run-alpipeline@v0.1
        with:
          version: ${{env.version}}
          appVersion: ${{env.appVersion}}
          appBuild: ${{env.appBuild}}
          appRevision: ${{env.appRevision}}
          InsiderSasToken: ${{ secrets.InsiderSasToken }}
          LicenseFile: ${{ secrets.LicenseFile }}
          CodeSignCertPfxFile: ${{ secrets.CodeSignCertPfxFile }}
          CodeSignCertPfxPassword: ${{ secrets.CodeSignCertPfxPassword }}

      - name: Publish Test Results
        uses: mikepenz/action-junit-report@v1
        with:
          report_paths: 'testresults*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}