name: "Next Major"

on:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:

env:
  version: nextmajor
  appVersion: '19.1'
  appBuild: 2147483647
  appRevision: 0

defaults:
  run:
    shell: PowerShell

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure key vault - Get Secrets
        uses: Azure/get-keyvault-secrets@v1.2
        with:
          keyvault: "juliandittmann"
          secrets: 'CodeSignCertPfxFile, CodeSignCertPfxPassword, InsiderSasToken'
        id: azureGetSecretAction

      - name: Run pipeline
        uses: juliandittmann/run-alpipeline@v0.1
        with:
          version: ${{env.version}}
          appVersion: ${{env.appVersion}}
          appBuild: ${{env.appBuild}}
          appRevision: ${{env.appRevision}}
          ApplicationInsightsKey: ${{ secrets.ApplicationInsightsKey }}
          InsiderSasToken: ${{ steps.azureGetSecretAction.outputs.InsiderSasToken }}
          CodeSignCertPfxFile: ${{ steps.azureGetSecretAction.outputs.CodeSignCertPfxFile }}
          CodeSignCertPfxPassword: ${{ steps.azureGetSecretAction.outputs.CodeSignCertPfxPassword }}

      - name: Publish Test Results
        uses: mikepenz/action-junit-report@v1
        with:
          report_paths: 'testresults*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}